"""Native PDF regions in the shared top-down source coordinate contract."""

from __future__ import annotations

import math
import re
from typing import Any

from opendoc_model import DocumentPage, PageGeometry, Rect2D, with_page_geometry

_NUMBER = r"(?:null|[+-]?(?:\d+(?:\.\d*)?|\.\d+)(?:[eE][+-]?\d+)?)"
_XYZ = re.compile(r"\[\s*(\d+)\s+0\s+R\s*/XYZ\s+(" + _NUMBER + r")\s+(" + _NUMBER + r")\s+(" + _NUMBER + r")\s*\]")


def native_xyz_destination(pdf: Any, xref: int) -> tuple[int, float | None, float | None, float | None] | None:
    for key in ("A/D", "Dest"):
        kind, raw = pdf.xref_get_key(xref, key)
        if kind != "array" or len(raw) > 1024:
            continue
        match = _XYZ.fullmatch(raw)
        if match is not None:
            values = tuple(None if item == "null" else float(item) for item in match.groups()[1:])
            if any(v is not None and (not math.isfinite(v) or abs(v) > 1_000_000) for v in values):
                raise ValueError("Invalid native PDF destination coordinates")
            return int(match[1]), *values
    return None

def read_page_geometry(page: Any, identifier: str) -> DocumentPage:
    """Use x=PDF x, y=-PDF y; crop is resolved before page rotation."""
    media, crop = page.mediabox, page.cropbox
    unit_kind, raw_unit = page.parent.xref_get_key(page.xref, "UserUnit")
    unit = 1.0 if unit_kind == "null" else float(raw_unit)
    if not math.isfinite(unit) or unit <= 0:
        raise ValueError("Invalid PDF UserUnit")
    if unit != 1:
        return DocumentPage(identifier, media.width*unit, media.height*unit, extra={
            "pdf_rotation": int(page.rotation), "coordinate_space": "pymupdf-unrotated",
            "pdf_user_unit": unit, "pdf_page_geometry_unsupported": "user-unit",
        })
    region = Rect2D(media.x0, -media.y1, media.width, media.height)
    visible = Rect2D(crop.x0, crop.y0-media.y1, crop.width, crop.height)
    implicit = page.parent.xref_get_key(page.xref, "CropBox")[0] == "null" and visible == region
    geometry = PageGeometry(region, None if implicit else visible, rotation=page.rotation)
    return with_page_geometry(DocumentPage(
        identifier, media.width, media.height,
        extra={"pdf_rotation": int(page.rotation), "coordinate_space": "pymupdf-unrotated",
               "pdf_page_geometry_imported": True},
    ), geometry)


def apply_page_geometry(page: Any, geometry: PageGeometry, source_origin: tuple[float, float]) -> tuple[float, float]:
    """Place our newly rendered crop-local content in native media coordinates."""
    pdf = page.parent
    if len(source_origin) != 2:
        raise ValueError("Invalid PDF source coordinate origin")
    media, crop = geometry.media_box, geometry.crop_box or geometry.media_box
    values = (*source_origin, media.x, media.y, media.width, media.height, crop.x, crop.y, crop.width, crop.height)
    if any(type(v) not in (int, float) or not math.isfinite(v) or abs(v) > 1_000_000 for v in values):
        raise ValueError("Invalid or excessive PDF page geometry")
    height = page.cropbox.height
    translation = source_origin[0], -source_origin[1]-height
    contents = page.get_contents()
    if contents:
        prefix, suffix = pdf.get_new_xref(), pdf.get_new_xref()
        pdf.update_object(prefix, "<< >>")
        pdf.update_object(suffix, "<< >>")
        pdf.update_stream(prefix, f"q\n1 0 0 1 {translation[0]:.10f} {translation[1]:.10f} cm\n".encode("ascii"))
        pdf.update_stream(suffix, b"\nQ\n")
        refs = " ".join(f"{xref} 0 R" for xref in (prefix, *contents, suffix))
        pdf.xref_set_key(page.xref, "Contents", f"[{refs}]")
    for key, region in (("MediaBox", media), ("CropBox", crop)):
        raw = (region.x, -region.y-region.height, region.x+region.width, -region.y)
        pdf.xref_set_key(page.xref, key, "[" + " ".join(f"{v:.10f}" for v in raw) + "]")
    if geometry.crop_box is None:
        pdf.xref_set_key(page.xref, "CropBox", "null")
    page.set_rotation(geometry.rotation)
    return translation


def translate_generated_links(pdf: Any, placements: dict[int, tuple[float, float]], links: dict[int, list[int]]) -> None:
    """Translate only native link rectangles/actions generated by our layout writer."""
    for page_xref, xrefs in links.items():
        tx, ty = placements.get(page_xref, (0, 0))
        for xref in xrefs:
            kind, raw = pdf.xref_get_key(xref, "Rect")
            if kind == "array":
                values = [float(item) for item in raw.strip("[]").split()]
                if len(values) != 4:
                    raise ValueError("Invalid generated link rectangle")
                values = [value + (tx if i % 2 == 0 else ty) for i, value in enumerate(values)]
                pdf.xref_set_key(xref, "Rect", "[" + " ".join(f"{value:.10f}" for value in values) + "]")
            for key in ("A/D", "Dest"):
                kind, raw = pdf.xref_get_key(xref, key)
                match = _XYZ.fullmatch(raw) if kind == "array" else None
                if match is None:
                    continue
                delta = placements.get(int(match[1]), (0, 0))
                values = [match[2], match[3], match[4]]
                for offset in (0, 1):
                    if values[offset] != "null":
                        values[offset] = f"{float(values[offset])+delta[offset]:.10f}"
                pdf.xref_set_key(xref, key, f"[{match[1]} 0 R /XYZ " + " ".join(values) + "]")
